"""Auto-tuned block sizes for ragged paged attention v3.

The v3 kernel splits into three pallas_calls (DECODE / PREFILL / MIXED), each
with its own (bq_sz, bkv_sz, bq_csz, bkv_csz) 4-tuple. This table is keyed by
device + stage + sliding-window bucket + the same workload signature used by v2.

Schema:
    TUNED_BLOCK_SIZES_V3[device_name][key] = (bq_sz, bkv_sz, bq_csz, bkv_csz)
    key = (stage, sliding_window, q_dtype, kv_dtype, q_heads, kv_heads,
           head_dim, page_size, max_num_tokens)
    stage in {"d", "p", "m"}
    sliding_window: None for full-attention layers; int for SWA layers
                    (a different sliding_window value is a different entry —
                    e.g., bkv ~= sliding_window is usually optimal so SWA must
                    not share a bucket with non-SWA).

bq_sz / bkv_sz / bq_csz / bkv_csz are in tokens (not pages). Generated by
benchmark/kernels/flash_attention/get_block_spec_config_v3.py.
"""

import logging

from sgl_jax.srt.kernels.ragged_paged_attention.tuned_block_sizes import (
    get_simplified_key,
)
from sgl_jax.srt.kernels.ragged_paged_attention.util import get_tpu_version

logger = logging.getLogger(__name__)

# Track which (stage, key) combos we've already warned about, so each unique
# lookup miss prints at most once per process. Helps diagnose "tuned table
# was added but server still falls back to heuristic" bugs (usually a shape
# mismatch — e.g., wrong q_heads_per_shard, or SWA layer hitting non-SWA key).
_WARNED_MISSES: set[tuple] = set()


TUNED_BLOCK_SIZES_V3: dict[str, dict[tuple, tuple[int, int, int, int]]] = {
    "TPU v5": {},
    "TPU v6e": {
        # ===== v6e production-shape sweep (2026-05-29 / 2026-05-30) =====
        # Tuned on tpuv6e-256-node, kernel commit c86d0ef499c3 (probe/rpa-v3-kv-len-v6e).
        # Tuner: get_block_spec_config_v3.py with --write-threshold-pct 0.0 (all
        # winners with positive delta are emitted, no skip).
        # Test conditions:
        #   - mid-kv data-gen: random_prefix_lens ∈ [1024, 2048), actual_kv ≈ 1500
        #   - max_context_len=40960, max_kv_cache_tokens=600000
        #   - tries=3 (variance bound, observed std/mean < 0.5%)
        # Source experiments:
        #   - exp-r4je7j87w7  hd=128 non-SWA (38 entries; final 4 cells lost to
        #                     8h timeout, prefill q=8 kv=8 ps=256 mnt=1024 missing)
        #   - exp-zydqhexohw  hd=192 non-SWA (16 entries — MiMo full-attn layers)
        #   - exp-lrcl0zt04q  hd=256 non-SWA (2 entries — Gemma full-attn layers)
        # Coverage matrix (per-shard shapes after typical TP split):
        #   hd=128: q∈{2,4,8,16}, kv∈{1,2,4,8} — Llama / Qwen2/3 / GLM-4 /
        #            Qwen3-32B / Ling-1T / Qwen-7B at TP={4,8,16}
        #   hd=192: q∈{4,8,16,32}, kv∈{1,2}   — MiMo-V2-Flash / V2.5-Pro full layers
        #   hd=256: q=2, kv=1                  — Gemma-2 full layers
        #
        # Open gaps (not in this drop, see follow-up issue):
        #   1. SWA layers (sliding_window=128 / 4096) — g3/g5 didn't schedule on
        #      v6e queue, will retry. Until then, MiMo SWA layers + Gemma SWA
        #      layers fall back to heuristic. Production trace shows heuristic
        #      bkv=256 with sw=128 already runs OK.
        #   2. Long actual_kv decode (16k+) — entries here are mid-kv tuned.
        #      Probe 1 single-shape data shows bkv=2048 is ~20% suboptimal at
        #      actual_kv≈24k (heuristic bkv=32768 wins long-kv coincidentally).
        #      Cross-shape long-kv probe pending.
        #   3. SMEM-pruned prefill cells (ps=128 mnt≥1024, ps=256 mnt≥2048 at
        #      max_context_len=40960) — physically unreachable in the kernel at
        #      that max_context_len; runtime uses chunk_prefill_size to keep
        #      mnt within tunable range.
        #
        # Pattern observation: across hd∈{128,192,256} × q×kv combos × ps×mnt,
        # mid-kv decode winner is uniformly bkv=2048 csz=2048. Deltas vs
        # heuristic +5%~+84% (depending on heuristic over-allocation severity).
        # Prefill ps=256 mnt=1024 winner is mostly (32, 1024, 32, 1024).
        # ----- hd=128 decode (non-SWA) -----
        ("d", None, "bfloat16", "bfloat16", 2, 1, 128, 128, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 2, 1, 128, 128, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 1, 128, 128, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 1, 128, 128, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 2, 128, 128, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 2, 128, 128, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 4, 128, 128, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 4, 128, 128, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 1, 128, 128, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 1, 128, 128, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 4, 128, 128, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 4, 128, 128, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 8, 128, 128, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 8, 128, 128, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 16, 2, 128, 128, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 16, 2, 128, 128, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 2, 1, 128, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 2, 1, 128, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 1, 128, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 1, 128, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 2, 128, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 2, 128, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 4, 128, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 4, 128, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 1, 128, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 1, 128, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 4, 128, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 4, 128, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 8, 128, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 8, 128, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 16, 2, 128, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 16, 2, 128, 256, 256): (1, 2048, 1, 2048),
        # ----- hd=128 prefill (chunked, ps=256 mnt=1024) -----
        ("p", None, "bfloat16", "bfloat16", 2, 1, 128, 256, 1024): (32, 1024, 32, 1024),
        ("p", None, "bfloat16", "bfloat16", 4, 1, 128, 256, 1024): (32, 1024, 32, 1024),
        ("p", None, "bfloat16", "bfloat16", 4, 2, 128, 256, 1024): (32, 1024, 32, 1024),
        ("p", None, "bfloat16", "bfloat16", 4, 4, 128, 256, 1024): (32, 1024, 32, 1024),
        ("p", None, "bfloat16", "bfloat16", 8, 1, 128, 256, 1024): (32, 1024, 32, 1024),
        ("p", None, "bfloat16", "bfloat16", 8, 4, 128, 256, 1024): (32, 1024, 32, 1024),
        # ----- hd=192→256 (key normalized) decode (MiMo full-attention layers) -----
        # Note: actual head_dim=192 normalizes to 256 in key per
        # `(head_dim + 127) // 128 * 128`.
        ("d", None, "bfloat16", "bfloat16", 4, 1, 256, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 1, 256, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 4, 1, 256, 256, 1024): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 1, 256, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 1, 256, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 8, 1, 256, 256, 1024): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 16, 1, 256, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 16, 1, 256, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 16, 1, 256, 256, 1024): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 1024): (1, 2048, 1, 2048),
        # ----- hd=192→256 prefill (MiMo full, chunked) -----
        ("p", None, "bfloat16", "bfloat16", 4, 1, 256, 256, 1024): (32, 1024, 32, 1024),
        ("p", None, "bfloat16", "bfloat16", 8, 1, 256, 256, 1024): (32, 1024, 32, 512),
        ("p", None, "bfloat16", "bfloat16", 16, 1, 256, 256, 1024): (32, 1024, 32, 512),
        ("p", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 1024): (32, 512, 32, 512),
        # ----- hd=256 decode (Gemma-2 full-attention layers) -----
        ("d", None, "bfloat16", "bfloat16", 2, 1, 256, 128, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 2, 1, 256, 128, 256): (1, 2048, 1, 2048),
    },
    "TPU v7": {
        # ===== MiMo-V2-Pro non-SWA (full-attention) layers =====
        # Per-shard shape: q_heads=32 kv_heads=2 head_dim=192→256 page_size=256
        # (tp_size=32, dp_size=8 → attention TP=4 → q=128/4=32, kv=8/4=2).
        # Tuned 2026-05-27 on tpuv7x-64-node with patched kernel fd69b77c9.
        #
        # Decode (mnt = BSZ): heuristic bkv=1024 loses to bkv=2048 by
        # ~18-25% across BSZ {4..512}. BSZ {1,2} skipped (delta <10%).
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 4): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 8): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 16): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 32): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 64): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 128): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 256): (1, 2048, 1, 2048),
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 512): (1, 2048, 1, 2048),
        # Large-mnt decode entries. Server actually pads decode max_q to 1024
        # or 2048 buckets at warmup (despite BSZ being smaller).
        ("d", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 1024): (1, 2048, 1, 2048),
        # Prefill at chunk_prefill_size=2048: heuristic bq=4 bkv=1024 loses
        # to bq=32 bkv=512 by +75%. Heuristic bq=min(MAX_BQ=32, max_q//2)
        # gives bq=4 when max_q=8 (post page-alignment), 8× too small.
        ("p", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 2048): (32, 512, 32, 512),
        # Mixed at small mnt buckets {8..1024}. Server precompiles these at
        # warmup for chunked-prefill / mixed-batch decode. Winners shift with
        # mnt: very small bq tracks mnt, mid range hits MAX_BQ=32 + bkv=256,
        # large range bumps bkv to 512.
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 8): (8, 256, 8, 256),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 16): (16, 256, 16, 256),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 32): (32, 256, 32, 256),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 64): (32, 256, 32, 256),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 128): (32, 256, 32, 256),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 256): (32, 256, 32, 256),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 512): (32, 512, 32, 512),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 1024): (32, 512, 32, 512),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 2048): (32, 512, 32, 512),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 4096): (32, 512, 32, 512),
        ("m", None, "bfloat16", "bfloat16", 32, 2, 256, 256, 8192): (32, 512, 32, 512),
        # ===== MiMo-V2-Pro SWA (sliding-window) layers =====
        # sliding_window=128 (= MiMo attention_chunk_size). Tuned 2026-05-27,
        # exp-szoo9187lg. Heuristic picks bkv=256 (page-aligned sliding_window
        # of 128); tuner finds bkv=512 wins +3-8% across all mnt buckets.
        # mnt=4 skipped (heur == best). Note bkv can't be < page_size=256 —
        # kernel asserts bkv_sz % page_size == 0.
        # p/m stages SMEM-pruned (page_indices > 1MB) — fall back to heuristic
        # (bkv=1024) on lookup miss.
        ("d", 128, "bfloat16", "bfloat16", 32, 2, 256, 256, 8): (1, 512, 1, 512),
        ("d", 128, "bfloat16", "bfloat16", 32, 2, 256, 256, 16): (1, 512, 1, 512),
        ("d", 128, "bfloat16", "bfloat16", 32, 2, 256, 256, 32): (1, 512, 1, 512),
        ("d", 128, "bfloat16", "bfloat16", 32, 2, 256, 256, 64): (1, 512, 1, 512),
        ("d", 128, "bfloat16", "bfloat16", 32, 2, 256, 256, 128): (1, 512, 1, 512),
        ("d", 128, "bfloat16", "bfloat16", 32, 2, 256, 256, 256): (1, 512, 1, 512),
        ("d", 128, "bfloat16", "bfloat16", 32, 2, 256, 256, 512): (1, 512, 1, 512),
        ("d", 128, "bfloat16", "bfloat16", 32, 2, 256, 256, 1024): (1, 512, 1, 512),
    },
}


def get_tuned_block_sizes_v3(
    stage: str,
    q_dtype,
    kv_dtype,
    actual_num_q_heads: int,
    actual_num_kv_heads: int,
    head_dim: int,
    page_size: int,
    max_num_tokens: int,
    sliding_window: int | None = None,
) -> tuple[int, int, int, int] | None:
    """Look up (bq_sz, bkv_sz, bq_csz, bkv_csz) from the v3 tuned table.

    sliding_window is part of the key — SWA layers need different block sizes
    than full-attention (bkv≈sliding_window is usually optimal for SWA to avoid
    loading KV that gets masked out anyway). None = full attention.

    Returns None if no entry matches; caller should fall back to the heuristic
    in ragged_paged_attention_v3.get_default_block_sizes.
    """
    if stage not in ("d", "p", "m"):
        raise ValueError(f"stage must be one of d/p/m, got {stage!r}")

    tpu_version = get_tpu_version()
    if tpu_version < 5:
        return None

    device_name, *signature = get_simplified_key(
        page_size,
        q_dtype,
        kv_dtype,
        actual_num_q_heads,
        actual_num_kv_heads,
        head_dim,
        max_num_tokens,
    )

    table = TUNED_BLOCK_SIZES_V3.get(device_name)
    if not table:
        return None

    key = (stage, sliding_window, *signature)
    hit = table.get(key)
    if hit is None and key not in _WARNED_MISSES:
        _WARNED_MISSES.add(key)
        logger.info(
            "RPA v3 tuned-block-size LOOKUP MISS device=%s key=%s "
            "(falling back to heuristic). Add this key to TUNED_BLOCK_SIZES_V3 "
            "to enable tuning for this shape.",
            device_name,
            key,
        )
    return hit
