apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sglang-jax
  description: JAX backend for SGL
  annotations:
    github.com/project-slug: Rodrian7/sglang-jax
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: experimental
  owner: guests
